### ISSUE TITLE
Is there problem connecting with elicznik page?

### ISSUE THREAD

**Issue by leszekw83** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#35] opened 2021-10-07 13:13 UTC
Hello, Tauron managed to change my energy meter, and after logging to website I see usage. I wanted to add component to HA, but after providing username/pass/meterNumber I constantly get that integration cannot connect to elicznik server:(

**Comment by leszekw83** [comment] 2021-10-07 13:43
> Do you have the latest version of integration?

Yes 2.0.4.

**Comment by PiotrMachowski** [comment] 2021-10-12 08:07
I have the same tariff and it works for me.

Does graphs on elicznik website show any data?

**Comment by leszekw83** [comment] 2021-11-16 14:16
Hello, still no data, got only an info message from supervisor log:

2021-11-16 15:12:52 WARNING (MainThread) [homeassistant.components.sensor] Updating tauron_amiplus sensor took longer than the scheduled update interval 0:00:30

Is there any way to debug deeper the integration? To check where is the problem?

**Comment by Hewelius** [comment] 2021-12-21 13:51
Hello there,
Do faced someone a problem with integration adding with
"Expecting value: line 1 column 1 (char 0)" and additionally cannot connect to the elicznik?
 Thanks

**Comment by MarcinKnD** [comment] 2022-01-09 12:15
I have a problem with integrate. I got error that it can connect to the server. What to do??

![1](https://user-images.githubusercontent.com/37018109/148681733-227c607e-1ef1-4e4d-8248-12e39094961d.png)
![2](https://user-images.githubusercontent.com/37018109/148681734-c53744c9-b303-4eb5-b4bd-e6fbb3e18e7b.png)
r

**Comment by pswid** [comment] 2022-02-03 09:36
I also have G13 tariff and have the same problem. Log show only:
`ERROR (MainThread) [custom_components.tauron_amiplus.config_flow] string indices must be integers`

I noticed that the data presented on the Tauron e-licznik website is very often incomplete _(Pobrano niekompletne dane. Prezentacja będzie dostępna po uzyskaniu danych z licznika)._ Could this have an impact on integration?

![image](https://user-images.githubusercontent.com/78219494/152316277-0faebea1-90b2-4dcd-b990-58b6f28507b1.png)

**Comment by PiotrMachowski** [comment] 2022-02-03 09:40
@pswid yup, it usually is the cause of the problem

**Comment by pswid** [comment] 2022-02-03 11:17
You're right. I've added the integration manually (in yaml file) with disabled consumption/generation_daily and it works!
However I'd like not to lose the functionality of daily consumption/generation monitoring. Would you be so nice and improve the integration to not fail (and reporting daily usage and generation) even when the data from e-licznik is incomplete? It would also be useful to have an additional binary entity informing about whether the data from the e-licznik is complete or not. This would allow monitoring how often the data is not complete (e.g. to submit a complaint to Tauron) or just to display info at dashboard that data from e-licznik is not accurate...

**Comment by PiotrMachowski** [comment] 2022-02-03 11:35
I plan to do some fixes soon, this will be one of them

**Comment by PiotrMachowski** [comment] 2022-04-28 03:03
Fixed in `v2.1.0`

**Closed by PiotrMachowski** 2022-04-28 03:03 UTC
