### ISSUE TITLE
Energy meter missing daily consumption 

### ISSUE THREAD

**Issue by max1984** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#33] opened 2021-09-27 09:29 UTC
For energy meter drop down list only monthly and yearly sensor shows up, missing daily. 
my core-2021.9.7

**Comment by PiotrMachowski** [comment] 2021-09-27 11:25
Duplicate of #31

**Closed by PiotrMachowski** 2021-09-27 11:25 UTC

**Comment by PiotrMachowski** [comment] 2023-01-18 09:06
I have changed approach and added importing data directly to statistics.
Since `v2.3.0` hourly readings are visible in Energy dashboard
