### ISSUE TITLE
Log Details (ERROR)

### ISSUE THREAD

**Issue by adamj3000** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#123] opened 2023-04-11 04:35 UTC
Hi Piotr,

Can you help with below error? please

This error originated from a custom integration.

Logger: custom_components.tauron_amiplus.coordinator
Source: custom_components/tauron_amiplus/connector.py:193 
Integration: Tauron AMIplus (documentation, issues) 
First occurred: 04:03:46 (2 occurrences) 
Last logged: 04:04:00

Unexpected error fetching tauron_amiplus data: 'allData'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 250, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 29, in _async_update_data
    data = await self.hass.async_add_executor_job(self._update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/tauron_amiplus/coordinator.py", line 40, in _update
    return self.connector.get_raw_data()
  File "/config/custom_components/tauron_amiplus/connector.py", line 103, in get_raw_data
    data.consumption = self.get_data_set(generation=False)
  File "/config/custom_components/tauron_amiplus/connector.py", line 115, in get_data_set
    dataset.json_daily, dataset.daily_date = self.get_values_daily(generation)
  File "/config/custom_components/tauron_amiplus/connector.py", line 193, in get_values_daily
    while offset <= CONST_MAX_LOOKUP_RANGE and (data is None or len(data["data"]["allData"]) < 24):
KeyError: 'allData'

**Comment by PiotrMachowski** [comment] 2023-04-11 07:09
Duplicate of #122

**Closed by PiotrMachowski** 2023-04-11 07:09 UTC

**Comment by PiotrMachowski** [comment] 2023-04-11 08:59
> I am sorry but I am new to this, you mean to delete line 122 from connector.py ?

No, I mean that an issue for this problem has been already created [here](https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/issues/122)

> the second question I have is regarding calculating energy as a prosument. Where do I copy below code ? and do I need to modify anything ?

You have to put it in `configuration.yaml` after adjusting entity ids (`sensor.tauron_amiplus_123_yearly_energy_generation`, `sensor.tauron_amiplus_123_yearly_energy_consumption`)

**Comment by adamj3000** [comment] 2023-04-11 09:31
Super, Dziękuję nie bylem pewien czy piszemy tu po PL. Wszystko masz napisane po ANG. 

Trzymam kciuki bo integracja mega!

Pozdrawiam,
AJ
