### ISSUE TITLE
Entities generated by integration can not be used to track consumption

### ISSUE THREAD

**Issue by bboczar** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#25] opened 2021-09-15 19:17 UTC
Hello,
I see that right now entities generated by integration can not be used in Energy monitoring in HA. It would be nice to be able to track Grid consumption using this integration.
Is it possible to implement such possiibility?

**Comment by PiotrMachowski** [comment] 2021-09-15 21:53
It is a duplicate of issue #18

**Closed by PiotrMachowski** 2021-09-15 21:53 UTC
