### ISSUE TITLE
Unable to setup integration: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by kstaniek** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#24] opened 2021-09-12 17:49 UTC
Seems something has changed on tauron side and this integartion no longer works.

```
Logger: homeassistant.components.sensor
Source: custom_components/tauron_amiplus/sensor.py:166
Integration: Sensor (documentation, issues)
First occurred: 19:39:22 (7 occurrences)
Last logged: 19:39:35

tauron_amiplus: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 633, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 277, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/tauron_amiplus/sensor.py", line 209, in _update
    self.update_configuration()
  File "/config/custom_components/tauron_amiplus/sensor.py", line 245, in update_configuration
    config = TauronAmiplusSensor.calculate_configuration(self.username, self.password, self.meter_id,
  File "/config/custom_components/tauron_amiplus/sensor.py", line 166, in calculate_configuration
    json_data = response.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by maureis** [comment] 2021-09-15 21:08
@kstaniek can you log in https://elicznik.tauron-dystrybucja.pl/ and check you get the same warning like me in #26 ?

**Comment by kstaniek** [comment] 2021-09-16 05:37
Yes, same! It's duplicate. Sounds we need to get know what the max rate is and reduce pulling interval.

**Comment by PiotrMachowski** [comment] 2021-09-16 07:30
Duplicate of #23

**Closed** 2021-09-16 07:30 UTC
