### ISSUE TITLE
Max daily login attempts exceeded

### ISSUE THREAD

**Issue by maureis** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#26] opened 2021-09-15 21:05 UTC
I saw no new data are fetching from Tauron, so I checked website:

![image](https://user-images.githubusercontent.com/6088053/133508827-bc760f66-2fd6-4b30-bc3a-fdfc271d156f.png)

Is it possible to reduce updating for sensors?
Notice: I didn't logging in for many days.

**Comment by PiotrMachowski** [comment] 2021-09-16 07:28
Duplicate of #23

**Closed by PiotrMachowski** 2021-09-16 07:28 UTC
