### ISSUE TITLE
real reading of the tauron meter 

### ISSUE THREAD

**Issue by bratmat** [PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus#12] opened 2021-03-07 14:54 UTC
Hi
Is it possible to add  reading of  the tauron total counter  for production and consumption ? I need this to do some calculations

**Comment by PiotrMachowski** [comment] 2021-03-22 10:16
Duplicate of #6

**Closed by PiotrMachowski** 2021-03-22 10:16 UTC
Labels: enhancement
